export const members = [
  { id: 1, name: '森田ひかる', image: new URL('./assets/hikaru.jpg', import.meta.url).href },
  { id: 2, name: '山下瞳月', image: new URL('./assets/shiduki.jpg', import.meta.url).href },
  { id: 3, name: '田村保乃', image: new URL('./assets/hono.jpg', import.meta.url).href },
  { id: 4, name: '守屋麗奈', image: new URL('./assets/rena.jpg', import.meta.url).href },
  { id: 5, name: '山﨑天', image: new URL('./assets/ten.jpg', import.meta.url).href },
  { id: 6, name: '上村 莉菜', image: new URL('./assets/rina.jpg', import.meta.url).href },
  { id: 7, name: '小池 美波', image: new URL('./assets/minami.jpg', import.meta.url).href },
  { id: 8, name: '齋藤 冬優花', image: new URL('./assets/fuyuka.jpg', import.meta.url).href },
  { id: 9, name: '井上 梨名', image: new URL('./assets/inori.jpg', import.meta.url).href },
  { id: 10, name: '遠藤 光莉', image: new URL('./assets/hikari.jpg', import.meta.url).href },
  { id: 11, name: '大園 玲', image: new URL('./assets/rei.jpg', import.meta.url).href },
  { id: 12, name: '大沼 晶保', image: new URL('./assets/akiho.jpg', import.meta.url).href },
  { id: 13, name: '幸阪 茉里乃', image: new URL('./assets/marino.jpg', import.meta.url).href },
  { id: 14, name: '武元 唯衣', image: new URL('./assets/yui.jpg', import.meta.url).href },
  { id: 15, name: '藤吉 夏鈴', image: new URL('./assets/karin.jpg', import.meta.url).href },
  { id: 16, name: '増本 綺良', image: new URL('./assets/kira.jpg', import.meta.url).href },
  { id: 17, name: '松田 里奈', image: new URL('./assets/matsurina.jpg', import.meta.url).href },
  { id: 18, name: '石森 璃花', image: new URL('./assets/rika.jpg', import.meta.url).href },
  { id: 19, name: '遠藤 理子', image: new URL('./assets/riko.jpg', import.meta.url).href },
  { id: 20, name: '小田倉 麗奈', image: new URL('./assets/reina.jpg', import.meta.url).href },
  { id: 21, name: '小島 凪紗', image: new URL('./assets/nagisa.jpg', import.meta.url).href },
  { id: 22, name: '谷口 愛季', image: new URL('./assets/airi.jpg', import.meta.url).href },
  { id: 23, name: '中嶋 優月', image: new URL('./assets/yuduki.jpg', import.meta.url).href },
  { id: 24, name: '的野 美青', image: new URL('./assets/mio.jpg', import.meta.url).href },
  { id: 25, name: '向井 純葉', image: new URL('./assets/itoha.jpg', import.meta.url).href },
  { id: 26, name: '村井 優', image: new URL('./assets/yuu.jpg', import.meta.url).href },
  { id: 27, name: '村山 美羽', image: new URL('./assets/mio.jpg', import.meta.url).href }
  // 他のアイテムを追加
];